rules:
  border-zero: 2
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - 2
    - convention: hyphenatedbem
  declarations-before-nesting: 2
  empty-line-between-blocks:
    - 2
    - allow-single-line-rulesets: false
  extends-before-mixins: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    - convention: hyphenatedbem
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: true
  max-file-line-count:
    - 2
    - length: 600
  max-line-length:
    - 2
    - length: 200
  mixins-before-declarations: 2
  mixin-name-format:
    - 2
    - convention: hyphenatedbem
  no-attribute-selectors: 2
  no-combinators: 1
  no-css-comments: 0
  no-color-keywords:
    - 2
    - allow-rgba: true
  no-color-literals:
    - 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 2
  no-url-domains: 2
  no-vendor-prefixes: 2
  no-warn: 0
  one-declaration-per-line: 2
  property-sort-order: 0
  property-units:
    - 2
    - global:
        - em
        - ms
        - px
        - rem
        - s
        - vh
        - vw
  pseudo-element: 2
  shorthand-values: 1
  single-line-per-selector: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    - convention: hyphenatedbem
  zero-unit: 2
